### ISSUE TITLE
Seeing flutter error thrown

### ISSUE THREAD

**Issue by aanelson** [douglasiacovelli/page_view_dot_indicator#12] opened 2022-07-20 23:34 UTC
Hi, we have been using the library for a while now and has been great. We have been seeing some crashes come back in our crash reporting however.  Guessing it is unmounted or hasn't added the scroll controller into the scrollView yet.  

Non-fatal Exception: FlutterError
0  ???                            0x0 growable_array.Bad_state_No_element:_ + 353 (growable_array.dart:353)
1  ???                            0x0 _GrowableList.single (dart:core)
2  ???                            0x0 ScrollController.position + 109 (scroll_controller.dart:109)
3  ???                            0x0 _PageViewDotIndicatorState._getOffsetForCurrentPosition + 164 (indicator.dart:164)
4  ???                            0x0 _PageViewDotIndicatorState.scrollToCurrentPosition + 101 (indicator.dart:101)
5  ???                            0x0 _PageViewDotIndicatorState.initState.<fn> + 89 (indicator.dart:89)
6  ???                            0x0 SchedulerBinding._invokeFrameCallback + 1146 (binding.dart:1146)
7  ???                            0x0 SchedulerBinding.handleDrawFrame + 1091 (binding.dart:1091)
8  ???                            0x0 SchedulerBinding._handleDrawFrame + 997 (binding.dart:997)

**Comment by douglasiacovelli** [comment] 2022-07-22 01:39
Hey! Thanks for reporting. Do you have a sample project I can use to
reproduce the error?

Em qua., 20 de jul. de 2022 20:34, aanelson ***@***.***>
escreveu:

**Comment by douglasiacovelli** [comment] 2022-08-22 22:30
Thanks @ihavenoface5 for opening the PR and @aanelson for opening the issue. It's merged and released! Please let me know if the problem is solved in 2.0.1

**Comment by gmarizy** [comment] 2022-12-18 20:29
I got this error with 2.0.1, but as an edge case. When I witnessed this error, I was updating twice my navigation. I fixed my navigation update and this error disappeared.

**Comment by douglasiacovelli** [comment] 2022-12-20 16:56
Thanks for the report, @gmarizy! I'm closing the issue :)

**Closed by douglasiacovelli** 2022-12-20 16:56 UTC
