### ISSUE TITLE
Null check operator used on a null value (_maxScrollExtent is null)

### ISSUE THREAD

**Issue by jmgeffroy** [douglasiacovelli/page_view_dot_indicator#15] opened 2023-04-14 08:41 UTC
Hi, I'm facing a weird issue. I create a PageViewDotIndocator with currentPage = 0 and length = 12. I get the following stacktrace (see below).
The corresponding code in the PageViewDotIndocator code is:

```  
double get maxScrollExtent => _maxScrollExtent!;
```
I did a quick investigation but didn't find any clue. Any idea? My enclosing layout probably causes it, but this Null check error should probably not happen... 

```
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      ScrollPosition.maxScrollExtent (package:flutter/src/widgets/scroll_position.dart:145:49)
#1      _PageViewDotIndicatorState._getOffsetForCurrentPosition (package:page_view_dot_indicator/src/indicator.dart:172:36)
#2      _PageViewDotIndicatorState.scrollToCurrentPosition (package:page_view_dot_indicator/src/indicator.dart:109:26)
#3      _PageViewDotIndicatorState.didUpdateWidget (package:page_view_dot_indicator/src/indicator.dart:103:7)
#4      StatefulElement.update (package:flutter/src/widgets/framework.dart:5142:55)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
```

**Comment by douglasiacovelli** [comment] 2023-04-14 10:50
Hey Jean!
I'll try to reproduce it and investigate. Can you provide me a sample app with the layout that caused the issue or even showing the enclosing layout stack and parameters?

Mind that the lib uses a scroll view, so it's important to have the width fixed on the enclosing layout.

**Comment by douglasiacovelli** [comment] 2023-08-02 02:17
Closing due to inactivity. In case this ever happens again please let me know

**Closed by douglasiacovelli** 2023-08-02 02:17 UTC
